services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: event_organizer
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "${SPRING_DATASOURCE_PASSWORD}"
    volumes:
      - db-data:/var/lib/postgresql/data

  app:
    build:
      context: .
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: "${SPRING_DATASOURCE_URL}"
      SPRING_DATASOURCE_USERNAME: "${SPRING_DATASOURCE_USERNAME}"
      SPRING_DATASOURCE_PASSWORD: "${SPRING_DATASOURCE_PASSWORD}"
    depends_on:
      - db
    ports:
      - "8080:8080"

volumes:
  db-data:
